In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Check TensorFlow version
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.18.0


In [3]:
# Creating Tensors
scalar = tf.constant(7)
vector = tf.constant([10, 20, 30])
matrix = tf.constant([[1, 2], [3, 4]])
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [4]:
# Printing tensors
print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:", matrix)
print("3D Tensor:", tensor_3d)

Scalar: tf.Tensor(7, shape=(), dtype=int32)
Vector: tf.Tensor([10 20 30], shape=(3,), dtype=int32)
Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
3D Tensor: tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [8]:
# Basic Tensor Operations
addition = tf.add(vector, 5)
subtraction = tf.subtract(matrix, 1)
multiplication = tf.multiply(vector, 2)
division = tf.divide(tf.cast(matrix, tf.float32), tf.constant(2.0))
tf.print("Addition:", addition)
tf.print("Subtraction:", subtraction)
tf.print("Multiplication:", multiplication)
tf.print("Division:", division)

Addition: [15 25 35]
Subtraction: [[0 1]
 [2 3]]
Multiplication: [20 40 60]
Division: [[0.5 1]
 [1.5 2]]


In [9]:
# Matrix Operations
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])
matmul = tf.matmul(matrix_a, matrix_b)
tf.print("Matrix Multiplication:", matmul)

Matrix Multiplication: [[19 22]
 [43 50]]


In [10]:
# Reshaping and Transposing
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
reshaped = tf.reshape(tensor, [3, 2])
transposed = tf.transpose(tensor)
tf.print("Reshaped:", reshaped)
tf.print("Transposed:", transposed)

Reshaped: [[1 2]
 [3 4]
 [5 6]]
Transposed: [[1 4]
 [2 5]
 [3 6]]


In [11]:
# Broadcasting
a = tf.constant([1, 2, 3])
b = tf.constant([[1], [2], [3]])
broadcasted_addition = a + b
tf.print("Broadcasted Addition:", broadcasted_addition)

Broadcasted Addition: [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [12]:
# Einsum Operations
A = tf.random.uniform((2, 3))
B = tf.random.uniform((3, 4))
C = tf.einsum('ij,jk->ik', A, B)  # Standard matrix multiplication

tf.print("Einsum Matrix Multiplication:", C)

D = tf.random.uniform((2, 3, 4))
E = tf.einsum('ijk->kji', D)  # Transposing dimensions

tf.print("Einsum Transposition:", E)

F = tf.random.uniform((3, 3))
trace = tf.einsum('ii->', F)  # Trace of a matrix

tf.print("Einsum Trace:", trace)

Einsum Matrix Multiplication: [[1.22434437 0.962166 0.815783799 1.42187083]
 [1.08030283 1.09927857 0.790816903 1.42237115]]
Einsum Transposition: [[[0.522013307 0.747698307]
  [0.548325896 0.505363226]
  [0.724085808 0.198139906]]

 [[0.638690233 0.852764249]
  [0.977901697 0.57374382]
  [0.907387733 0.231413603]]

 [[0.468432188 0.935683846]
  [0.60052526 0.257638574]
  [0.94331038 0.0135850906]]

 [[0.945683122 0.405556798]
  [0.0604630709 0.169381738]
  [0.267076731 0.918637514]]]
Einsum Trace: 1.94817746


In [13]:
# Reductions
mean = tf.reduce_mean(tensor)
sum_all = tf.reduce_sum(tensor)
max_value = tf.reduce_max(tensor)

tf.print("Mean:", mean)
tf.print("Sum:", sum_all)
tf.print("Max:", max_value)

Mean: 3
Sum: 21
Max: 6
